In [19]:
import numpy as np
import pandas as pd

In [20]:
df_onu = pd.read_excel("../data/raw/onu_populacao_idade_sexo.xlsx", skiprows=15)

df_onu.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111
0,Index,Variant,"Region, subregion, country or area *",Notes,Location code,ISO3 Alpha-code,ISO2 Alpha-code,SDMX code**,Type,Parent code,...,91,92,93,94,95,96,97,98,99,100+
1,1,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,253.868,186.0435,132.9005,87.4855,57.6775,41.9175,29.5815,19.474,11.6965,14.593
2,2,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,256.192,181.824,129.718,90.5555,58.54,37.793,26.6935,18.3145,11.793,14.9565
3,3,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,256.8655,184.096,127.486,88.834,60.8535,38.674,24.392,16.7485,11.2085,15.411
4,4,Estimates,World,NaN,900,NaN,NaN,1,World,0,...,255.1835,185.3335,129.577,87.6905,59.855,40.209,25.0775,15.4535,10.349,15.4325

In [21]:
df_onu.info()

<class 'pandas.DataFrame'>
RangeIndex: 21984 entries, 0 to 21983
Columns: 112 entries, Unnamed: 0 to Unnamed: 111
dtypes: object(107), str(5)
memory usage: 18.8+ MB

In [22]:
df_onu.describe()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111
count,21984,21984,21984,5555,21984,17539,17465,20943,21984,21984,...,21984,21984,21984,21984,21984,21984,21984,21984,21984,21984
unique,21984,2,301,47,303,238,237,282,10,38,...,9992,9341,8593,7885,7164,6460,5836,5181,4578,4973
top,Index,Estimates,Latin America and the Caribbean,2,900,BDI,BI,419,Country/Area,915,...,0,0,0,0,0,0,0,0,0,0
freq,1,21983,148,814,74,74,74,148,17538,2072,...,530,680,896,1189,1572,2008,2585,3314,4164,4968

In [26]:
coluna_10 = df_onu.iloc[:, 10]
print(coluna_10)

0        Year
1        1950
2        1951
3        1952
4        1953
         ...
21979    2019
21980    2020
21981    2021
21982    2022
21983    2023
Name: Unnamed: 10, Length: 21984, dtype: object

In [27]:
coluna_11 = df_onu.iloc[:, 11]
print(coluna_11)

0                 0
1        81507.1885
2         83568.469
3         86252.372
4        88590.8955
            ...
21979        0.1325
21980         0.126
21981        0.1055
21982         0.099
21983         0.096
Name: Total population by single age, both sexes combined (thousands), Length: 21984, dtype: object